version: "3.9"  # optional since v1.27.0
services:
  api:
    image: 4108748/ocr-base-image
    container_name: api
    working_dir: '/usr/src/app/'
    command: bash -c "rq worker --url redis://redis & uvicorn main:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app/
    links:
      - redis

  redis:
    image: redis
